version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=inventory_db
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=supersecretkey
      - NODE_ENV=development

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: inventory_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
